SELECT X.Nome,X.CONTADOR FROM (
SELECT AUTOR.Nome AS Nome, count(LIVRO.Autor) AS CONTADOR
FROM LIVRO
RIGHT JOIN AUTOR
ON AUTOR.CodAutor = LIVRO.Autor
GROUP BY AUTOR.CodAutor
ORDER BY CONTADOR ASC) X WHERE CONTADOR = ( SELECT MIN(MENOR) FROM (SELECT AUTOR.Nome AS Nome, count(LIVRO.Autor) AS MENOR
FROM LIVRO
RIGHT JOIN AUTOR
ON AUTOR.CodAutor = LIVRO.Autor
GROUP BY AUTOR.CodAutor
ORDER BY CONTADOR ASC)Y);
